source ~/.zplug/init.zsh

setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS

if [ -n "$MSYSTEM" ]; then
    unsetopt promptcr
    if [ -f /tmp/ssh-agent-env ]; then
        . /tmp/ssh-agent-env
    fi
    zplug 'dracula/zsh', as:theme
else
    zplug mafredri/zsh-async, from:github
    zplug sindresorhus/pure, use:pure.zsh, from:github, as:theme
fi

zplug "b4b4r07/enhancd", use:init.sh
# ENHANCD_FILTER=fzf; export ENHANCD_FILTER

HISTFILE=${ZSH_HISTORY:-~/.zsh_history}
HISTSIZE=10000
SAVEHIST=10000

function peco-select-history() {
#    BUFFER=$(\history -n 1 | tac | awk '!a[$0]++' | fzf --query "$LBUFFER")
    BUFFER=$(\history -n 1 | fzf --tac --query "$LBUFFER")
    CURSOR=$#BUFFER
    # zle clear-screen
}
zle -N peco-select-history
bindkey '^r' peco-select-history

function peco-src() {
   local src=$(ghq list --full-path | fzf --query "$LBUFFER")
   if [ -n "$src" ]; then
       BUFFER="cd $src"
       zle accept-line
   fi
   zle -R -c
}
zle -N peco-src
bindkey '^]' peco-src

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

export GOPATH=$HOME/dev
export PATH=$GOPATH/bin:$PATH
if [ -f ~/.bash_aliases ]; then
   . ~/.bash_aliases
fi

zplug load # --verbose
if type zprof > /dev/null 2>&1; then
    zprof | less
fi

if [ "$INSIDE_EMACS" ]; then
        TERM=eterm-color
fi
umask 022
export DISPLAY=localhost:0.0

(
    # command_path="/mnt/c/Program Files (x86)/VcXsrv/vcxsrv.exe"
    command_path="/mnt/c/Program Files/VcXsrv/vcxsrv.exe"
    command_name=$(basename "$command_path")
    if ! tasklist.exe 2> /dev/null | fgrep -q "$command_name"; then
        "$command_path" :0 -multiwindow -clipboard -wgl > /dev/null 2>&1 &
    fi
)
alias emacs="NO_AT_BRIDGE=1 LIBGL_ALWAYS_INDIRECT=1 emacs"
keychain -q ~/.ssh/id_rsa
source ~/.keychain/$HOSTNAME-sh
