(set-language-environment "Japanese")
(setq indent-tabs-mode t)
(setq *c-indent-tabs-mode* nil)
(setq default-tab-width 4)
(setq tab-width 4)
(setq make-backup-files nil)
(setq auto-save-default nil)
(setq auto-save-list-file-name nil)
(setq auto-save-list-file-prefix nil)
(setq show-paren-mode t)
(setq transient-mark-mode nil)
(set-language-environment 'utf-8)
(set-default-coding-systems 'utf-8)
